# ==========================================
# CONFIGURACIÓN GENERAL
# ==========================================
server.port=${PORT:8000}

# ==========================================
# SERVICIO EXTERNO (HEROKU)
# ==========================================
external.visitas.api.url=https://tupaginawebhoy-fe12dd345e09.herokuapp.com/api/visitas

# ==========================================
# THYMELEAF (vistas)
# ==========================================
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML5

# ==========================================
# CORREO (solo si se usa)
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tupaginawebhoy.mx@gmail.com
spring.mail.password=cnxgbdhafvqnpubt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# ==========================================
# SEGURIDAD (clave para AES)
# ==========================================
app.crypto.secret-key=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
app.timezone=Indian/Antananarivo

# ==========================================
# MULTIPART (subida de archivos)
# ==========================================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-swallow-size=10MB
server.tomcat.max-http-form-post-size=10MB

# ==========================================
# SWAGGER (deshabilitado)
# ==========================================
springdoc.api-docs.enabled=false