server.port=${PORT:8000}

#configuracion de la BD PostgresQL
spring.datasource.url=jdbc:postgresql://c5cqb8h0eop3g3.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/de2slot6r3tnv
spring.datasource.username=ufhtu34buhnp6k
spring.datasource.password=p1e65e58596c6f17b75ce0372a41a79b0402f0b12055a8bbfef33b8135580bc2b
#spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
#spring.datasource.hikari.auto-commit=true




#Configuraci�n JPA
#spring.jpa.hibernate.ddl-auto=none  
spring.jpa.show-sql=true
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
#spring.datasource.hikari.schema=registro

# Configuraci�n de HikariCP
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000 
# 30 segundos
spring.datasource.hikari.idle-timeout=600000 
# 10 minutos

#Para habilitar el template
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML5

###### Configuraci�n del Correo Gmail SMTP: tupaginawebhoy
spring.mail.host=smtp.gmail.com
spring.mail.port=587
#spring.mail.protocol=smtp
spring.mail.username=tupaginawebhoy.mx@gmail.com
spring.mail.password=cnxgbdhafvqnpubt 
#spring.mail.properties.smtp.ssl.enable=true
#gjqdrwgngbqkqign
##zvsmzliznnczymtk
##5XFS&&(Zt9rNIjwOC
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true
#spring.mail.properties.mail.smtp.quitwait=false
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


# Clave secreta para AES256 (debe tener 32 bytes para AES-256)
app.crypto.secret-key=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
# Zona horaria de Madagascar
app.timezone= Indian/Antananarivo   

springdoc.api-docs.enabled=false





# L�mite m�ximo de tama�o de solicitud (para JSON y formularios)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Tambi�n para el tama�o del cuerpo (si usas Tomcat)
server.tomcat.max-swallow-size=10MB
server.tomcat.max-http-form-post-size=10MB
