# ==========================================
# CONFIGURACI�N GENERAL
# ==========================================
server.port=${PORT:8000}

# ==========================================
# SERVICIO EXTERNO (HEROKU)
# ==========================================
# URL base de la API de Heroku (sin /api al final, se agrega en los servicios)
external.heroku.api.url=https://tupaginawebhoy-fe12dd345e09.herokuapp.com/api

# URL para visitas (usando la base)
external.visitas.api.url=${external.heroku.api.url}/visitas


# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML5
#Para habilitar el template