package com.AgroVeterinaria.Herramientas;
import java.sql.Date;
import java.sql.Time;
import javax.mail.MessagingException;
import javax.mail.internet.MimeMessage;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.mail.MailParseException;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;

import com.AgroVeterinaria.DTO.Articulo;
import com.AgroVeterinaria.DTO.Usuarios;
import com.AgroVeterinaria.Registro.LogUsuarios.DataSourceLogUsuarios;
import com.AgroVeterinaria.Registro.Usuarios.DataSourceUsuarios;

@Service
public class EmailService {
	@Autowired
	private JavaMailSender mailSender;

    @Autowired
    private DataSourceUsuarios dataSourceUsuarios;
    
	@Autowired
	private DataSourceLogUsuarios LogUsuariosRepository;
	
	
    public EmailService(JavaMailSender mailSender) {
        this.mailSender = mailSender;
    }
    
    //public void sendMail(String from, String to, String subject, String body, File... attachments);
    public void sendMail(String from, String to, String subject, String encode) {
 	    MimeMessage message =mailSender.createMimeMessage();
 	    String cuerpo = "";
 	    cuerpo = getHTML(encode, to).toString();
 	    //System.out.println("Cuerpo: " + cuerpo);
 	    try {
             message.setSubject(subject);
             message.setContent(message, "text/html");
             MimeMessageHelper helper;
             helper = new MimeMessageHelper(message, true);
             helper.setFrom(from);
             helper.setTo(to);
             helper.setText(cuerpo, true);
             mailSender.send(message);
 	    } catch (MessagingException e) {
 	        // Verificar si ya existe
            Date currentDate = new Date(System.currentTimeMillis());
            Time currentTime = new Time(System.currentTimeMillis());
 	    	Usuarios usuario = new Usuarios();
 	        Usuarios existente = dataSourceUsuarios.findByOrigenEMail(Constantes.ORIGEN, to);
 	        System.out.println(Constantes.ORIGEN);
 	        System.out.println("053-SndMail Existente: " + to + ":to,  existente:" + existente);
            usuario.setEstatus(Constantes.INT_ESTATUS_UNO); //Error en envío de Correo
            System.out.println("Usuario: " + usuario.toString() );
            int num1 = dataSourceUsuarios.usuarioUpdateEstatus(usuario);
            int num = LogUsuariosRepository.insertData(usuario.getOrigen(), usuario.getEmail(), currentDate, currentTime, "Error en Envío de Correo");             
 	        throw new MailParseException(e);
 	    }
    }
    public String getHTML(String encode, String correo) {
         String plantilla = "";
         String tabla = "";
         tabla = getConfirmaCorreo(encode, correo);
         plantilla = "<html><body>" + tabla + "</body></html>";
         //System.out.println("Plantilla: " + plantilla);
         return plantilla;
    }
    public String getConfirmaCorreo(String encode, String correo) {
         String Confirma = "";
         Confirma = "" +
                 "<table\n"
                 + "  align='center'\n"
                 + "  class='m_-container'\n"
                 + "  style='border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:inherit;width:632px;margin:0 auto;padding:0'\n"
                 + "  bgcolor='#ffffff'>"
                 + "  <tbody>\n"
                 + "    <tr style='vertical-align:top;padding:0' align='left'>\n"
                 + "      <td style='word-wrap:normal;border-collapse:collapse!important;padding:0' align='left' valign='top'>\n"
                 + "        <table style='border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:100%;display:table;padding:0'>\n"
                 + "          <tbody>\n"
                 + "            <tr style='vertical-align:top;padding:0' align='left'>\n"
                 + "              <td class='m_-small-12 m_-columns' style='word-wrap:normal;border-collapse:collapse!important;width:616px;margin:0 auto;padding:0 16px 16px' align='left' valign='top'>\n"
                 + "                <table style='border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:100%;padding:0'>\n"
                 + "                  <tbody>\n"
                 + "                    <tr style='vertical-align:top;padding:0' align='left'>\n"
                 + "                      <td style='word-wrap:normal;border-collapse:collapse!important;padding:0' align='left' valign='top'>\n"
                 + "                        <div  class='m_-header'\n"
                 + "                              style='padding-top:10px;padding-bottom:20px;border-bottom-width:1px;border-bottom-color:#d9d9d9;border-bottom-style:solid'>\n"
                 + "                              <table style='border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:100%;display:table;padding:0'>\n"
                 + "                                  <tbody>\n"
                 + "                                    <tr style='vertical-align:top;padding:0' align='left'>\n"
                 + "                                      <td class='m_-small-12 m_-columns'\n"
                 + "                                      style='word-wrap:normal;border-collapse:collapse!important;width:50%;margin:0 auto;padding:0'\n"
                 + "                                      align='left' valign='top'>\n"
                 + "                                        <div  class='m_-header__logo'\n"
                 + "                                              style='padding-top:10px;font-size:1.125rem;font-weight:bold;color:#f02d00'>\n"
                 + "                                              <a href='" + Constantes.URL_BASE + "'\n"
                 + "                                              style='color:#f02d00;text-decoration:none;display:inline-block;font-weight:bold'\n"
                 + "                                              target='_blank'\n"
                 + "                                              data-saferedirecturl='" + Constantes.URL_BASE + "'>\n"
                 + "                                              <img\n"
                 + "                                                alt='TuPaginaWebHoy'\n"
                 + "                                                src='" + Constantes.URL_BASE + "images/betha.svg'\n"
                 + "                                                style='outline:none;text-decoration:none;width:55px;max-width:100%;clear:both;display:inline-block;vertical-align:middle;border:none'\n"
                 + "                                                class='CToWUd'\n"
                 + "                                                data-bit='iit'>\n"
                 + "                                              </a>\n"
                 + "                                        </div>\n"
                 + ""
                 + "                                      </td>\n"
                 + "                                      <td class='m_-small-12 m_-columns'\n"
                 + "                                        style='word-wrap:normal;border-collapse:collapse!important;width:50%;margin:0 auto;padding:0' align='left' valign='top'>\n"
                 + "                                        <div class='m_-header__nav' style='margin-top:6px;padding-top:10px' align='right'>\n"
                 + "                                        <div class='m_-header__nav__item' style='display:inline-block;vertical-align:middle;margin-left:10px'>\n"
                 + "                                          <a\n"
                 + "                                            href='" + Constantes.URL_BASE + "'\n"
                 + "                                            style='color:#161616;text-decoration:underline'\n"
                 + "                                            target='_blank'\n"
                 + "                                            data-saferedirecturl='" + Constantes.URL_BASE + "'>\n"
                 + "                                            <img\n"
                 + "                                              style='outline:none;text-decoration:none;width:51px;max-width:100%;clear:both;display:inline;vertical-align:middle;border:none'\n"
                 + "                                              class='CToWUd'\n"
                 + "                                              data-bit='iit'>Productos</a>\n"
                 + "                                        </div>\n"
                 + "                                          <div class='m_-header__nav__item' style='display:inline-block;vertical-align:middle;margin-left:10px'>\n"
                 + "                                            <a href='" + Constantes.URL_BASE + "'\n"
                 + "                                            style='color:#161616;text-decoration:underline'\n"
                 + "                                            target='_blank'\n"
                 + "                                            data-saferedirecturl='" + Constantes.URL_BASE + "'>\n"
                 + "                                            <img\n"
                 + "                                              src='" + Constantes.URL_BASE + "images/icon-carrito.jpg'\n"
                 + "                                              style='outline:none;text-decoration:none;width:23px;max-width:100%;clear:both;display:inline;vertical-align:middle;border:none'\n"
                 + "                                              class='CToWUd'\n"
                 + "                                              data-bit='iit'>\n"
                 + "                                            </a>\n"
                 + "                                          </div>\n"
                 + "                                        </div>\n"
                 + "                                      </td>\n"
                 + "                                    <td class='m_-expander'\n"
                 + "                                        style='word-wrap:normal;border-collapse:collapse!important;width:0;padding:0'\n"
                 + "                                        align='left'\n"
                 + "                                        valign='top'>\n"
                 + "                                    </td>\n"
                 + "                                  </tr>\n"
                 + "                                </tbody>\n"
                 + "                              </table>\n"
                 + "                        </div>\n"
                 + "                      </td>\n"
                 + "                    </tr>\n"
                 + "                  </tbody>\n"
                 + "                </table>\n"
                 + "              </td>\n"
                 + "            </tr>\n"
                 + "          </tbody>\n"
                 + "        </table>\n"
                 + "        <table style='border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:100%;padding:0'>\n"
                 + "              <tbody>\n"
                 + "                <tr style='vertical-align:top;padding:0' align='left'>\n"
                 + "                  <td height='16px' style='font-size:16px;line-height:16px;word-wrap:normal;border-collapse:collapse!important;padding:0' align='left' valign='top'>\n"
                 + "                  </td>\n"
                 + "                </tr>\n"
                 + "              </tbody>\n"
                 + "        </table>\n"
                 + "        <table style='border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:100%;display:table;padding:0'>\n"
                 + "              <tbody>\n"
                 + "                <tr style='vertical-align:top;padding:0' align='left'>\n"
                 + "                  <td class='m_-small-12 m_-columns' style='word-wrap:normal;border-collapse:collapse!important;width:616px;margin:0 auto;padding:0 16px 16px' align='left' valign='top'>\n"
                 + "                    <table style='border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:100%;padding:0'>\n"
                 + "                      <tbody>\n"
                 + "                        <tr style='vertical-align:top;padding:0' align='left'>\n"
                 + "                          <th style='font-weight:normal'>\n"
                 + "                            <div align='center'>\n"
                 + "                              <div style='display:inline-block;border-radius:50%;box-sizing:content-box;width:72px;height:72px;border:1px solid #e8e8e8'>\n"
                 + "                                <img\n"
                 + "                                  src='" + Constantes.URL_BASE + "images/icon-user.jpg'\n"
                 + "                                  style='outline:none;text-decoration:none;width:auto;max-width:100%;clear:both;display:block;vertical-align:top;height:auto;border-radius:50%;color:transparent'\n"
                 + "                                  class='CToWUd'\n"
                 + "                                  data-bit='iit'>\n"
                 + "                              </div>\n"
                 + "                              <div>\n"
                 + "                              </div>\n"
                 + "                            </div>\n"
                 + "                            <h2 style='font-weight:500;line-height:1.29;word-wrap:normal;font-size:26px;margin:0 0 10px' align='center'>¡Te doy la bienvenida, " + correo +"! </h2>\n"
                 + "                            <div style='margin-bottom:30px;font-size:18px;color:#848484' align='center'>\n"
                 + "                              Confirma tu email haciendo clic en este enlace:\n"
                 + "                            </div>\n"
                 + "                            <p style='margin:0 0 20px' align='center'>\n"
                 + "                              <a"
                 + "                                class='m_-btn'"
                 + "                                href='" + Constantes.URL_BASE + "valida/" + encode +"' "
                 + "                                style='color:#f02d00;text-decoration:none;display:inline-block;font-weight:bold;line-height:18px;text-align:center;background-color:#ffffff;border-radius:3px;padding:6px 20px;border:1px solid rgba(240,45,0,0.3)'\n"
                 + "                                target='_blank'"
                 + "                                data-saferedirecturl='" + Constantes.URL_BASE + "valida/" + encode +"' >"
                 + "                                Confirmar email"
                 + "                              </a>"
                 + "                            </p>\n"
                 + "                          </th>\n"
                 + "                          <th class='m_-expander' style='width:0;font-weight:normal;padding:0'>\n"
                 + "                        </th>\n"
                 + "                      </tr>\n"
                 + "                    </tbody>\n"
                 + "                    </table>\n"
                 + "                </td>\n"
                 + "              </tr>\n"
                 + "            </tbody>\n"
                 + "        </table>\n"
                 + "        <table style='border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:100%;padding:0'>\n"
                 + "            <tbody>\n"
                 + "              <tr style='vertical-align:top;padding:0' align='left'>\n"
                 + "                <td height='32px' style='font-size:32px;line-height:32px;word-wrap:normal;border-collapse:collapse!important;padding:0'\n"
                 + "                    align='left' valign='top'>\n"
                 + "                </td>\n"
                 + "              </tr>\n"
                 + "            </tbody>\n"
                 + "        </table>\n"
                 + "        <table style='border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:100%;display:table;padding:0'>\n"
                 + "            <tbody>\n"
                 + "              <tr style='vertical-align:top;padding:0' align='left'>\n"
                 + "                <td class='m_-small-12 m_-columns'\n"
                 + "                    style='word-wrap:normal;border-collapse:collapse!important;width:616px;margin:0 auto;padding:0 16px 16px'\n"
                 + "                    align='left' valign='top'>\n"
                 + "                    <table style='border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:100%;padding:0'>\n"
                 + "                      <tbody>\n"
                 + "                        <tr style='vertical-align:top;padding:0' align='left'>\n"
                 + "                          <th style='padding-top:0;font-weight:normal'>\n"
                 + "                            <div class='m_-footer' style='font-size:0.75rem;color:#848484;background-color:#f2f2f2;padding:20px 0'>\n"
                 + "                              <div style='margin:0 16px'>\n"
                 + "                                <table style='border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:100%;display:table;padding:0'>\n"
                 + "                                  <tbody>\n"
                 + "                                    <tr style='vertical-align:top;padding:0' align='left'>\n"
                 + "                                      <td class='m_-small-12 m_-columns'\n"
                 + "                                          style='word-wrap:normal;border-collapse:collapse!important;width:50%;margin:0 auto;padding:0 0 16px'\n"
                 + "                                          align='left' valign='top'>\n"
                 + "                                          <table style='border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:100%;padding:0'>\n"
                 + "                                            <tbody>\n"
                 + "                                              <tr style='vertical-align:top;padding:0' align='left'>\n"
                 + "                                                <th style='font-weight:normal'>\n"
                 + "                                                  <small style='font-size:12px;color:#848484;display:block;margin-top:5px'>\n"
                 + "                                                    TuPaginaWebHoy Corp.\n"
                 + "                                                    <span>\n"
                 + "                                                      <span style='opacity:0'></span>\n"
                 + "                                                      2025\n"
                 + "                                                      <span style='opacity:0'></span>\n"
                 + "                                                      México,\n"
                 + "                                                      <span style='opacity:0'></span>\n"
                 + "                                                      Catemaco\n"
                 + "                                                    </span>\n"
                 + ""
                 + "                                                  </small>\n"
                 + "                                                </th>\n"
                 + "                                                <th class='m_-expander' style='width:0;font-weight:normal;padding:0'></th>\n"
                 + "                                              </tr>\n"
                 + "                                            </tbody>\n"
                 + "                                          </table>\n"
                 + "                                        </td>\n"
                 + "                                        <td class='m_-small-12 m_-columns'\n"
                 + "                                            style='word-wrap:normal;border-collapse:collapse!important;width:50%;margin:0 auto;padding:0 0 16px'\n"
                 + "                                            align='left' valign='top'>\n"
                 + "                                            <table style='border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:100%;padding:0'>\n"
                 + "                                              <tbody>\n"
                 + "                                                <tr style='vertical-align:top;padding:0' align='left'>\n"
                 + "                                                  <th style='font-weight:normal'>\n"
                 + "                                                    <div class='m_-footer__social' align='right'>\n"
                 + "                                                      <a href='https://www.facebook.com/SistemasBetha/'\n"
                 + "                                                         style='color:#161616;text-decoration:none'\n"
                 + "                                                         target='_blank'\n"
                 + "                                                         data-saferedirecturl='https://www.facebook.com/SistemasBetha/'>\n"
                 + "                                                        <img\n"
                 + "                                                          alt='Facebook'\n"
                 + "                                                          src='" + Constantes.URL_BASE + "images/face.png'\n"
                 + "                                                          style='outline:none;text-decoration:none;width:30px;max-width:100%;clear:both;display:inline;vertical-align:middle;border:none'\n"
                 + "                                                        class='CToWUd' data-bit='iit'>\n"
                 + "                                                      </a>\n"
                 + "                                                      <a href='https://twitter.com/Fernand89270455'\n"
                 + "                                                         style='color:#161616;text-decoration:none'\n"
                 + "                                                         target='_blank'\n"
                 + "                                                         data-saferedirecturl='https://twitter.com/Fernand89270455'>\n"
                 + "                                                        <img alt='Twitter'\n"
                 + "                                                             src='" + Constantes.URL_BASE + "images/Twitter.png'\n"
                 + "                                                             style='outline:none;text-decoration:none;width:30px;max-width:100%;clear:both;display:inline;vertical-align:middle;border:none'\n"
                 + "                                                             class='CToWUd'\n"
                 + "                                                             data-bit='iit'>\n"
                 + "                                                      </a>\n"
                 + "                                                      <a href='https://aboutme.google.com/?hl=es-419'\n"
                 + "                                                         style='color:#161616;text-decoration:none'\n"
                 + "                                                         target='_blank'\n"
                 + "                                                         data-saferedirecturl='https://api.whatsapp.com/send?phone=+525576806898&text=%22Hola%22'>\n"
                 + "                                                         <img alt='WhatsApp'\n"
                 + "                                                              src='" + Constantes.URL_BASE + "images/whatsapp.png'\n"
                 + "                                                              style='outline:none;text-decoration:none;width:30px;max-width:100%;clear:both;display:inline;vertical-align:middle;border:none'\n"
                 + "                                                              class='CToWUd' data-bit='iit'>\n"
                 + "                                                      </a>\n"
                 + "                                                    </div>\n"
                 + "                                                  </th>\n"
                 + "                                                  <th class='m_-expander' style='width:0;font-weight:normal;padding:0'>\n"
                 + "                                                  </th>\n"
                 + "                                                </tr>\n"
                 + "                                              </tbody>\n"
                 + "                                            </table>\n"
                 + "                                          </td>\n"
                 + "                                        </tr>\n"
                 + "                                      </tbody>\n"
                 + "                                    </table>\n"
                 + "                                  </div>\n"
                 + "                                  <div style='padding-top:16px;border-top-width:1px;border-top-color:#d9d9d9;border-top-style:solid;margin:0 16px' align='center'>\n"
                 + "                                    <small style='font-size:12px;color:#848484;display:block'>\n"
                 + "                                      <a\n"
                 + "                                        href='" + Constantes.URL_BASE + "'\n"
                 + "                                        style='color:#f02d00;text-decoration:underline'\n"
                 + "                                        target='_blank'\n"
                 + "                                        data-saferedirecturl='" + Constantes.URL_BASE + "'>\n"
                 + "                                        ¿Tienes alguna duda? Contáctanos vía Chat en Línea ubicado en la página principal.\n"
                 + "                                      </a>\n"
                 + "                                    </small>\n"
                 + "                                    <small style='font-size:12px;color:#848484;display:block;margin-top:10px'>\n"
                 + "                                      <a\n"
                 + "                                        href='" + Constantes.URL_BASE + "'\n"
                 + "                                        style='color:#848484;text-decoration:underline'\n"
                 + "                                        target='_blank'\n"
                 + "                                        data-saferedirecturl='" + Constantes.URL_BASE + "descargas/TUPAGINAWEBHOY-es.vcf'>\n"
                 + "                                        Añádenos a tu lista de contactos\n"
                 + "                                      </a>\n"
                 + "                                    </small>\n"
                 + ""
                 + "                                  </div>\n"
                 + "                                  <div style='padding-top:16px;margin:0 16px' align='center'>\n"
                 + "                                  <div>\n"
                 + "                                    <small style='font-size:12px;color:#848484;display:block'>\n"
                 + "                                      © 2018 TuPaginaWebHoy Corp.\n"
                 + "                                      <br>\n"
                 + "                                      <a\n"
                 + "                                        href='" + Constantes.URL_BASE + "condiciones'\n"
                 + "                                        style='color:#848484;text-decoration:underline'\n"
                 + "                                        target='_blank'\n"
                 + "                                        data-saferedirecturl='" + Constantes.URL_BASE + "condiciones'>\n"
                 + "                                        Condiciones de uso\n"
                 + "                                      </a>\n"
                 + "                                      |\n"
                 + "                                      <a\n"
                 + "                                        href='" + Constantes.URL_BASE + "aviso-privacidad'\n"
                 + "                                        style='color:#848484;text-decoration:underline'\n"
                 + "                                        target='_blank'\n"
                 + "                                        data-saferedirecturl='" + Constantes.URL_BASE + "aviso-privacidad'>\n"
                 + "                                        Aviso de privacidad\n"
                 + "                                      </a>\n"
                 + "                                      |\n"
                 + "                                      <a\n"
                 + "                                        href='" + Constantes.URL_BASE + "cookies'\n"
                 + "                                        style='color:#848484;text-decoration:underline'\n"
                 + "                                        target='_blank'\n"
                 + "                                        data-saferedirecturl='" + Constantes.URL_BASE + "cookies'>\n"
                 + "                                        Política de cookies\n"
                 + "                                      </a>\n"
                 + ""
                 + "                                    </small>\n"
                 + "                                  </div>\n"
                 + "                                </div>\n"
                 + "                                <div style='padding-top:16px;border-top-width:1px;border-top-color:#d9d9d9;border-top-style:solid;margin:20px 16px 0' align='center'>\n"
                 + "                                  <div style='font-size:15px'>\n"
                 + "                                    <div style='color:#505050'>\n"
                 + "                                      Próximamente! Descárgate la app TuPaginaWebHoy\n"
                 + "                                    </div>\n"
                 + "                                    <div>\n"
                 + "                                      <a\n"
                 + "                                        href='"+ Constantes.URL_APP_STORE + "' style='color:#161616;text-decoration:underline'\n"
                 + "                                        target='_blank'\n"
                 + "                                        data-saferedirecturl='"+ Constantes.URL_APP_STORE + "'>\n"
                 + "                                        <img\n"
                 + "                                          alt='App Store'\n"
                 + "                                          src='" + Constantes.URL_BASE + "images/app-store.jpg'\n"
                 + "                                          style='outline:none;text-decoration:none;width:auto;max-width:100%;clear:both;display:inline;vertical-align:middle;height:35px;margin:10px 2px 0;border:none'\n"
                 + "                                          class='CToWUd' data-bit='iit'>\n"
                 + "                                        </a>\n"
                 + "                                        <a\n"
                 + "                                          href='" + Constantes.URL_GOOGLE_PLAY + "'\n"
                 + "                                          style='color:#161616;text-decoration:underline'\n"
                 + "                                          target='_blank'\n"
                 + "                                          data-saferedirecturl='" + Constantes.URL_GOOGLE_PLAY + "'>\n"
                 + "                                          <img\n"
                 + "                                            alt='Google Play'\n"
                 + "                                            src='" + Constantes.URL_BASE + "images/google-play.jpg'\n"
                 + "                                            style='outline:none;text-decoration:none;width:auto;max-width:100%;clear:both;display:inline;vertical-align:middle;height:35px;margin:10px 2px 0;border:none'\n"
                 + "                                            class='CToWUd'\n"
                 + "                                            data-bit='iit'>\n"
                 + "                                          </a>\n"
                 + "                                        </div>\n"
                 + "                                      </div>\n"
                 + ""
                 + "                                    </div>\n"
                 + "                                  </div>\n"
                 + "                                </th>\n"
                 + "                                <th class='m_-expander' style='width:0;font-weight:normal;padding:0'>\n"
                 + "                                </th>\n"
                 + "                              </tr>\n"
                 + "                            </tbody>\n"
                 + "                          </table>\n"
                 + "                        </td>\n"
                 + "                      </tr>\n"
                 + "                    </tbody>\n"
                 + "        </table>\n"
                 + "        <table  class='m_-hidden-tablet'\n"
                 + "                style='border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:100%;padding:0'>\n"
                 + "            <tbody>\n"
                 + "              <tr style='vertical-align:top;padding:0' align='left'>\n"
                 + "               <td height='32px' style='font-size:32px;line-height:32px;word-wrap:normal;border-collapse:collapse!important;padding:0' align='left' valign='top'>\n"
                 + "               </td>\n"
                 + "              </tr>\n"
                 + "            </tbody>\n"
                 + "        </table>\n"
                 + "      </td>\n"
                 + "    </tr>\n"
                 + "  </tbody>\n"
                 + "</table>\n"
                 + "";
         return Confirma;
     }



    public void sendMailGenerico(Articulo articulo, String from, String to, String subject, String encode, String fecha, String hora) {
        MimeMessage message =mailSender.createMimeMessage();
        String cuerpo = "";
        cuerpo = getHTMLGenerico(articulo, encode, to, fecha, hora).toString();
        //System.out.println("Cuerpo: " + cuerpo);
        try {
            message.setSubject(subject);
            message.setContent(message, "text/html");
            MimeMessageHelper helper;
            helper = new MimeMessageHelper(message, true);
            helper.setFrom(from);
            helper.setTo(to);
            helper.setText(cuerpo, true);
            mailSender.send(message);
        } catch (MessagingException e) {
            throw new MailParseException(e);
        }
    }
    public String getHTMLGenerico(Articulo articulo, String encode, String correo, String fecha, String hora) {
        String plantilla = "";
        String tabla = "";
        tabla = getConfirmaCorreoGenerico(articulo, encode, correo, fecha, hora);
        plantilla = "<html><body>" + tabla + "</body></html>";
        //System.out.println("Plantilla: " + plantilla);
        return plantilla;
    }
    public String getConfirmaCorreoGenerico(Articulo articulo, String encode, String correo, String fecha, String hora) {
        String Confirma = "";
        Confirma = "" +
                "<table\n"
                + "  align='center'\n"
                + "  class='m_-container'\n"
                + "  style='border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:inherit;width:632px;margin:0 auto;padding:0'\n"
                + "  bgcolor='#ffffff'>"
                + "  <tbody>\n"
                + "    <tr style='vertical-align:top;padding:0' align='left'>\n"
                + "      <td style='word-wrap:normal;border-collapse:collapse!important;padding:0' align='left' valign='top'>\n"
                + "        <table style='border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:100%;display:table;padding:0'>\n"
                + "          <tbody>\n"
                + "            <tr style='vertical-align:top;padding:0' align='left'>\n"
                + "              <td class='m_-small-12 m_-columns' style='word-wrap:normal;border-collapse:collapse!important;width:616px;margin:0 auto;padding:0 16px 16px' align='left' valign='top'>\n"
                + "                <table style='border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:100%;padding:0'>\n"
                + "                  <tbody>\n"
                + "                    <tr style='vertical-align:top;padding:0' align='left'>\n"
                + "                      <td style='word-wrap:normal;border-collapse:collapse!important;padding:0' align='left' valign='top'>\n"
                + "                        <div  class='m_-header'\n"
                + "                              style='padding-top:10px;padding-bottom:20px;border-bottom-width:1px;border-bottom-color:#d9d9d9;border-bottom-style:solid'>\n"
                + "                              <table style='border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:100%;display:table;padding:0'>\n"
                + "                                  <tbody>\n"
                + "                                    <tr style='vertical-align:top;padding:0' align='left'>\n"
                + "                                      <td class='m_-small-12 m_-columns'\n"
                + "                                      style='word-wrap:normal;border-collapse:collapse!important;width:50%;margin:0 auto;padding:0'\n"
                + "                                      align='left' valign='top'>\n"
                + "                                        <div  class='m_-header__logo'\n"
                + "                                              style='padding-top:10px;font-size:1.125rem;font-weight:bold;color:#f02d00'>\n"
                + "                                              <a href='" + Constantes.URL_BASE + "'\n"
                + "                                              style='color:#f02d00;text-decoration:none;display:inline-block;font-weight:bold'\n"
                + "                                              target='_blank'\n"
                + "                                              data-saferedirecturl='" + Constantes.URL_BASE + "'>\n"
                + "                                              <img\n"
                + "                                                alt='TuPaginaWebHoy'\n"
                + "                                                src='" + Constantes.URL_BASE + "images/betha.svg'\n"
                + "                                                style='outline:none;text-decoration:none;width:55px;max-width:100%;clear:both;display:inline-block;vertical-align:middle;border:none'\n"
                + "                                                class='CToWUd'\n"
                + "                                                data-bit='iit'>\n"
                + "                                              </a>\n"
                + "                                        </div>\n"
                + ""
                + "                                      </td>\n"
                + "                                      <td class='m_-small-12 m_-columns'\n"
                + "                                        style='word-wrap:normal;border-collapse:collapse!important;width:50%;margin:0 auto;padding:0' align='left' valign='top'>\n"
                + "                                        <div class='m_-header__nav' style='margin-top:6px;padding-top:10px' align='right'>\n"
                + "                                        <div class='m_-header__nav__item' style='display:inline-block;vertical-align:middle;margin-left:10px'>\n"
                + "                                          <a\n"
                + "                                            href='" + Constantes.URL_BASE + "'\n"
                + "                                            style='color:#161616;text-decoration:underline'\n"
                + "                                            target='_blank'\n"
                + "                                            data-saferedirecturl='" + Constantes.URL_BASE + "'>\n"
                + "                                            <img\n"
                + "                                              style='outline:none;text-decoration:none;width:51px;max-width:100%;clear:both;display:inline;vertical-align:middle;border:none'\n"
                + "                                              class='CToWUd'\n"
                + "                                              data-bit='iit'>Productos</a>\n"
                + "                                        </div>\n"
                + "                                          <div class='m_-header__nav__item' style='display:inline-block;vertical-align:middle;margin-left:10px'>\n"
                + "                                            <a href='" + Constantes.URL_BASE + "'\n"
                + "                                            style='color:#161616;text-decoration:underline'\n"
                + "                                            target='_blank'\n"
                + "                                            data-saferedirecturl='" + Constantes.URL_BASE + "'>\n"
                + "                                            <img\n"
                + "                                              src='" + Constantes.URL_BASE + "images/icon-carrito.jpg'\n"
                + "                                              style='outline:none;text-decoration:none;width:23px;max-width:100%;clear:both;display:inline;vertical-align:middle;border:none'\n"
                + "                                              class='CToWUd'\n"
                + "                                              data-bit='iit'>\n"
                + "                                            </a>\n"
                + "                                          </div>\n"
                + "                                        </div>\n"
                + "                                      </td>\n"
                + "                                    <td class='m_-expander'\n"
                + "                                        style='word-wrap:normal;border-collapse:collapse!important;width:0;padding:0'\n"
                + "                                        align='left'\n"
                + "                                        valign='top'>\n"
                + "                                    </td>\n"
                + "                                  </tr>\n"
                + "                                </tbody>\n"
                + "                              </table>\n"
                + "                        </div>\n"
                + "                      </td>\n"
                + "                    </tr>\n"
                + "                  </tbody>\n"
                + "                </table>\n"
                + "              </td>\n"
                + "            </tr>\n"
                + "          </tbody>\n"
                + "        </table>\n"
                + "        <table style='border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:100%;padding:0'>\n"
                + "              <tbody>\n"
                + "                <tr style='vertical-align:top;padding:0' align='left'>\n"
                + "                  <td height='16px' style='font-size:16px;line-height:16px;word-wrap:normal;border-collapse:collapse!important;padding:0' align='left' valign='top'>\n"
                + "                  </td>\n"
                + "                </tr>\n"
                + "              </tbody>\n"
                + "        </table>\n"
                + "        <table style='border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:100%;display:table;padding:0'>\n"
                + "              <tbody>\n"
                + "                <tr style='vertical-align:top;padding:0' align='left'>\n"
                + "                  <td class='m_-small-12 m_-columns' style='word-wrap:normal;border-collapse:collapse!important;width:616px;margin:0 auto;padding:0 16px 16px' align='left' valign='top'>\n"
                + "                    <table style='border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:100%;padding:0'>\n"
                + "                      <tbody>\n"
                + "                        <tr style='vertical-align:top;padding:0' align='left'>\n"
                + "                          <th style='font-weight:normal'>\n"
                + "                            <div align='center'>\n"
                + "                              <div style='display:inline-block;border-radius:50%;box-sizing:content-box;width:72px;height:72px;border:1px solid #e8e8e8'>\n"
                + "                                <img\n"
                + "                                  src='" + Constantes.URL_BASE + "images/icon-user.jpg'\n"
                + "                                  style='outline:none;text-decoration:none;width:auto;max-width:100%;clear:both;display:block;vertical-align:top;height:auto;border-radius:50%;color:transparent'\n"
                + "                                  class='CToWUd'\n"
                + "                                  data-bit='iit'>\n"
                + "                              </div>\n"
                + "                              <div>\n"
                + "                              </div>\n"
                + "                            </div>\n"
                + "                            <h2 style='font-weight:500;line-height:1.29;word-wrap:normal;font-size:26px;margin:0 0 10px' align='center'>¡Gracias por tu comentario, " + correo +"! </h2>\n"
                + "                            <div style='margin-bottom:30px;font-size:18px;color:#848484' align='center'>\n"
                + "                              Haz clic en el botón 'Confirmar email' para mostrar tu comentario:\n"
                + "                            </div>\n"
                + "                            <p style='margin:0 0 20px' align='center'>\n"
                + "                              <a"
                + "                                class='m_-btn'"
                + "                                href='" + Constantes.URL_BASE  + articulo.getUrlBase() + "/" + articulo.getUrlOrigen() +"/"+ encode +"/" + fecha + "/" +hora+"' "
                + "                                style='color:#f02d00;text-decoration:none;display:inline-block;font-weight:bold;line-height:18px;text-align:center;background-color:#ffffff;border-radius:3px;padding:6px 20px;border:1px solid rgba(240,45,0,0.3)'\n"
                + "                                target='_blank'"
                + "                                data-saferedirecturl='" + Constantes.URL_BASE + articulo.getUrlBase() + "/" + articulo.getUrlOrigen() +"/"+ encode +"/" + fecha + "/" +hora+"' >"
                + "                                Confirmar email"
                + "                              </a>"
                + "                            </p>\n"
                + "                          </th>\n"
                + "                          <th class='m_-expander' style='width:0;font-weight:normal;padding:0'>\n"
                + "                        </th>\n"
                + "                      </tr>\n"
                + "                    </tbody>\n"
                + "                    </table>\n"
                + "                </td>\n"
                + "              </tr>\n"
                + "            </tbody>\n"
                + "        </table>\n"
                + "        <table style='border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:100%;padding:0'>\n"
                + "            <tbody>\n"
                + "              <tr style='vertical-align:top;padding:0' align='left'>\n"
                + "                <td height='32px' style='font-size:32px;line-height:32px;word-wrap:normal;border-collapse:collapse!important;padding:0'\n"
                + "                    align='left' valign='top'>\n"
                + "                </td>\n"
                + "              </tr>\n"
                + "            </tbody>\n"
                + "        </table>\n"
                + "        <table style='border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:100%;display:table;padding:0'>\n"
                + "            <tbody>\n"
                + "              <tr style='vertical-align:top;padding:0' align='left'>\n"
                + "                <td class='m_-small-12 m_-columns'\n"
                + "                    style='word-wrap:normal;border-collapse:collapse!important;width:616px;margin:0 auto;padding:0 16px 16px'\n"
                + "                    align='left' valign='top'>\n"
                + "                    <table style='border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:100%;padding:0'>\n"
                + "                      <tbody>\n"
                + "                        <tr style='vertical-align:top;padding:0' align='left'>\n"
                + "                          <th style='padding-top:0;font-weight:normal'>\n"
                + "                            <div class='m_-footer' style='font-size:0.75rem;color:#848484;background-color:#f2f2f2;padding:20px 0'>\n"
                + "                              <div style='margin:0 16px'>\n"
                + "                                <table style='border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:100%;display:table;padding:0'>\n"
                + "                                  <tbody>\n"
                + "                                    <tr style='vertical-align:top;padding:0' align='left'>\n"
                + "                                      <td class='m_-small-12 m_-columns'\n"
                + "                                          style='word-wrap:normal;border-collapse:collapse!important;width:50%;margin:0 auto;padding:0 0 16px'\n"
                + "                                          align='left' valign='top'>\n"
                + "                                          <table style='border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:100%;padding:0'>\n"
                + "                                            <tbody>\n"
                + "                                              <tr style='vertical-align:top;padding:0' align='left'>\n"
                + "                                                <th style='font-weight:normal'>\n"
                + "                                                  <small style='font-size:12px;color:#848484;display:block;margin-top:5px'>\n"
                + "                                                    TuPaginaWebHoy Corp.\n"
                + "                                                    <span>\n"
                + "                                                      <span style='opacity:0'></span>\n"
                + "                                                      2025\n"
                + "                                                      <span style='opacity:0'></span>\n"
                + "                                                      México,\n"
                + "                                                      <span style='opacity:0'></span>\n"
                + "                                                      Catemaco\n"
                + "                                                    </span>\n"
                + ""
                + "                                                  </small>\n"
                + "                                                </th>\n"
                + "                                                <th class='m_-expander' style='width:0;font-weight:normal;padding:0'></th>\n"
                + "                                              </tr>\n"
                + "                                            </tbody>\n"
                + "                                          </table>\n"
                + "                                        </td>\n"
                + "                                        <td class='m_-small-12 m_-columns'\n"
                + "                                            style='word-wrap:normal;border-collapse:collapse!important;width:50%;margin:0 auto;padding:0 0 16px'\n"
                + "                                            align='left' valign='top'>\n"
                + "                                            <table style='border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:100%;padding:0'>\n"
                + "                                              <tbody>\n"
                + "                                                <tr style='vertical-align:top;padding:0' align='left'>\n"
                + "                                                  <th style='font-weight:normal'>\n"
                + "                                                    <div class='m_-footer__social' align='right'>\n"
                + "                                                      <a href='https://www.facebook.com/SistemasBetha/'\n"
                + "                                                         style='color:#161616;text-decoration:none'\n"
                + "                                                         target='_blank'\n"
                + "                                                         data-saferedirecturl='https://www.facebook.com/SistemasBetha/'>\n"
                + "                                                        <img\n"
                + "                                                          alt='Facebook'\n"
                + "                                                          src='" + Constantes.URL_BASE + "images/face.png'\n"
                + "                                                          style='outline:none;text-decoration:none;width:30px;max-width:100%;clear:both;display:inline;vertical-align:middle;border:none'\n"
                + "                                                        class='CToWUd' data-bit='iit'>\n"
                + "                                                      </a>\n"
                + "                                                      <a href='https://twitter.com/Fernand89270455'\n"
                + "                                                         style='color:#161616;text-decoration:none'\n"
                + "                                                         target='_blank'\n"
                + "                                                         data-saferedirecturl='https://twitter.com/Fernand89270455'>\n"
                + "                                                        <img alt='Twitter'\n"
                + "                                                             src='" + Constantes.URL_BASE + "images/Twitter.png'\n"
                + "                                                             style='outline:none;text-decoration:none;width:30px;max-width:100%;clear:both;display:inline;vertical-align:middle;border:none'\n"
                + "                                                             class='CToWUd'\n"
                + "                                                             data-bit='iit'>\n"
                + "                                                      </a>\n"
                + "                                                      <a href='https://aboutme.google.com/?hl=es-419'\n"
                + "                                                         style='color:#161616;text-decoration:none'\n"
                + "                                                         target='_blank'\n"
                + "                                                         data-saferedirecturl='https://api.whatsapp.com/send?phone=+525576806898&text=%22Hola%22'>\n"
                + "                                                         <img alt='WhatsApp'\n"
                + "                                                              src='" + Constantes.URL_BASE + "images/whatsapp.png'\n"
                + "                                                              style='outline:none;text-decoration:none;width:30px;max-width:100%;clear:both;display:inline;vertical-align:middle;border:none'\n"
                + "                                                              class='CToWUd' data-bit='iit'>\n"
                + "                                                      </a>\n"
                + "                                                    </div>\n"

                + "                                                  </th>\n"
                + "                                                  <th class='m_-expander' style='width:0;font-weight:normal;padding:0'>\n"
                + "                                                  </th>\n"
                + "                                                </tr>\n"
                + "                                              </tbody>\n"
                + "                                            </table>\n"
                + "                                          </td>\n"
                + "                                        </tr>\n"
                + "                                      </tbody>\n"
                + "                                    </table>\n"
                + "                                  </div>\n"
                + "                                  <div style='padding-top:16px;border-top-width:1px;border-top-color:#d9d9d9;border-top-style:solid;margin:0 16px' align='center'>\n"
                + "                                    <small style='font-size:12px;color:#848484;display:block'>\n"
                + "                                      <a\n"
                + "                                        href='" + Constantes.URL_BASE + "'\n"
                + "                                        style='color:#f02d00;text-decoration:underline'\n"
                + "                                        target='_blank'\n"
                + "                                        data-saferedirecturl='" + Constantes.URL_BASE + "'>\n"
                + "                                        ¿Tienes alguna duda? Contáctanos vía Chat en Línea ubicado en la página principal.\n"
                + "                                      </a>\n"
                + "                                    </small>\n"
                + "                                    <small style='font-size:12px;color:#848484;display:block;margin-top:10px'>\n"
                + "                                      <a\n"
                + "                                        href='" + Constantes.URL_BASE + "'\n"
                + "                                        style='color:#848484;text-decoration:underline'\n"
                + "                                        target='_blank'\n"
                + "                                        data-saferedirecturl='" + Constantes.URL_BASE + "descargas/IGLESIASATANICA-es.vcf'>\n"
                + "                                        Añádenos a tu lista de contactos\n"
                + "                                      </a>\n"
                + "                                    </small>\n"
                + ""
                + "                                  </div>\n"
                + "                                  <div style='padding-top:16px;margin:0 16px' align='center'>\n"
                + "                                  <div>\n"
                + "                                    <small style='font-size:12px;color:#848484;display:block'>\n"
                + "                                      © 2018 TuPaginaWebHoy Corp.\n"
                + "                                      <br>\n"
                + "                                      <a\n"
                + "                                        href='" + Constantes.URL_BASE + "condiciones'\n"
                + "                                        style='color:#848484;text-decoration:underline'\n"
                + "                                        target='_blank'\n"
                + "                                        data-saferedirecturl='" + Constantes.URL_BASE + "condiciones'>\n"
                + "                                        Condiciones de uso\n"
                + "                                      </a>\n"
                + "                                      |\n"
                + "                                      <a\n"
                + "                                        href='" + Constantes.URL_BASE + "aviso-privacidad'\n"
                + "                                        style='color:#848484;text-decoration:underline'\n"
                + "                                        target='_blank'\n"
                + "                                        data-saferedirecturl='" + Constantes.URL_BASE + "aviso-privacidad'>\n"
                + "                                        Aviso de privacidad\n"
                + "                                      </a>\n"
                + "                                      |\n"
                + "                                      <a\n"
                + "                                        href='" + Constantes.URL_BASE + "cookies'\n"
                + "                                        style='color:#848484;text-decoration:underline'\n"
                + "                                        target='_blank'\n"
                + "                                        data-saferedirecturl='" + Constantes.URL_BASE + "cookies'>\n"
                + "                                        Política de cookies\n"
                + "                                      </a>\n"
                + ""
                + "                                    </small>\n"
                + "                                  </div>\n"
                + "                                </div>\n"
                + "                                <div style='padding-top:16px;border-top-width:1px;border-top-color:#d9d9d9;border-top-style:solid;margin:20px 16px 0' align='center'>\n"
                + "                                  <div style='font-size:15px'>\n"
                + "                                    <div style='color:#505050'>\n"
                + "                                      Próximamente! Descárgate la app TuPaginaWebHoy\n"
                + "                                    </div>\n"
                + "                                    <div>\n"
                + "                                      <a\n"
                + "                                        href='" + Constantes.URL_APP_STORE + "' style='color:#161616;text-decoration:underline'\n"
                + "                                        target='_blank'\n"
                + "                                        data-saferedirecturl='" + Constantes.URL_APP_STORE + "'>\n"
                + "                                        <img\n"
                + "                                          alt='App Store'\n"
                + "                                          src='" + Constantes.URL_BASE + "images/app-store.jpg'\n"
                + "                                          style='outline:none;text-decoration:none;width:auto;max-width:100%;clear:both;display:inline;vertical-align:middle;height:35px;margin:10px 2px 0;border:none'\n"
                + "                                          class='CToWUd' data-bit='iit'>\n"
                + "                                        </a>\n"
                + "                                        <a\n"
                + "                                          href='" + Constantes.URL_GOOGLE_PLAY + "'\n"
                + "                                          style='color:#161616;text-decoration:underline'\n"
                + "                                          target='_blank'\n"
                + "                                          data-saferedirecturl='" + Constantes.URL_GOOGLE_PLAY + "'>\n"
                + "                                          <img\n"
                + "                                            alt='Google Play'\n"
                + "                                            src='" + Constantes.URL_BASE + "images/google-play.jpg'\n"
                + "                                            style='outline:none;text-decoration:none;width:auto;max-width:100%;clear:both;display:inline;vertical-align:middle;height:35px;margin:10px 2px 0;border:none'\n"
                + "                                            class='CToWUd'\n"
                + "                                            data-bit='iit'>\n"
                + "                                          </a>\n"
                + "                                        </div>\n"
                + "                                      </div>\n"
                + ""
                + "                                    </div>\n"
                + "                                  </div>\n"
                + "                                </th>\n"
                + "                                <th class='m_-expander' style='width:0;font-weight:normal;padding:0'>\n"
                + "                                </th>\n"
                + "                              </tr>\n"
                + "                            </tbody>\n"
                + "                          </table>\n"
                + "                        </td>\n"
                + "                      </tr>\n"
                + "                    </tbody>\n"
                + "        </table>\n"
                + "        <table  class='m_-hidden-tablet'\n"
                + "                style='border-spacing:0;border-collapse:collapse;vertical-align:top;text-align:left;width:100%;padding:0'>\n"
                + "            <tbody>\n"
                + "              <tr style='vertical-align:top;padding:0' align='left'>\n"
                + "               <td height='32px' style='font-size:32px;line-height:32px;word-wrap:normal;border-collapse:collapse!important;padding:0' align='left' valign='top'>\n"
                + "               </td>\n"
                + "              </tr>\n"
                + "            </tbody>\n"
                + "        </table>\n"
                + "      </td>\n"
                + "    </tr>\n"
                + "  </tbody>\n"
                + "</table>\n"
                + "";
        return Confirma;
   }
    
}